plugins = {

--Kernel [SECTION]
{ name = "Adrenaline by TheOfficialFloW (Fix double touch)", id = "ADRENALINE.png", path = "adrenaline_kernel.skprx", section = "KERNEL", version = "0001", desc = LANGUAGE["INSTALLP_DESC_ADRENALINE"], KEY = "INSTALLP_DESC_ADRENALINE", link = "https://raw.githubusercontent.com/TheOfficialFloW/Adrenaline/master/readme.md", },

{ name = "0syscall6 by SKGleba", id = "REFOOD_SYSCALL.png", path = "0syscall6.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_SYSCALL6"], KEY = "INSTALLP_DESC_SYSCALL6",
  crc = 0xda05f49b, v = "v1.3",  version = "0002", link = "https://raw.githubusercontent.com/SKGleba/0syscall6/master/README.md", },
{ name = "8BitVita by Ibrahim778", id = "EBITVITA.png", path = "8BitVita.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_8BIVITA"], KEY = "INSTALLP_DESC_8BIVITA",
  crc = 0xbb96537, v = "v1.2",  version = "0001", link = "https://raw.githubusercontent.com/Ibrahim778/8BitVita/master/README.md", },
{ name = "Dumping addcont IDs by cuevavirus", id = "DUMPADDCONTIDS.png", path = "aciddumper.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_ACIDDUMPER"], KEY = "INSTALLP_DESC_ACIDDUMPER",
  crc = 0xb59fba61, v = "v1.0.0", version = "0002", link = "https://raw.githubusercontent.com/cuevavirus/AddcontIDDumper/master/README.md", },
{ name = "AnalogStickDisable by Hack-Usagi", id = "ANALOGDISABLE.png", path = "AnalogStickDisable.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_ANALOGSTICK"], KEY = "INSTALLP_DESC_ANALOGSTICK",
  crc = 0x23e8e05a, v = "v1.1",  version = "0002", link = "https://raw.githubusercontent.com/Hack-Usagi/AnalogStickDisable/master/README.md", },
{ name = "AnalogStickDisable Left To Right by Yoti", id = "ANALOGDISABLELR.png", path = "AnalogStickDisable_LeftToRight.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_ANALOGSTICK1"], KEY = "INSTALLP_DESC_ANALOGSTICK1",
  crc = 0x1a7bfb22, v = "v1.2", version = "0001", link = "https://raw.githubusercontent.com/Yoti/AnalogStickDisable/master/README.md", },
{ name = "AnalogStickDisable Left Only by Hack-Usagi", id = "ANALOGDISABLELEFT.png", path = "AnalogStickDisable_LeftOnly.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_ANALOGSTICK4"], KEY = "INSTALLP_DESC_ANALOGSTICK4",
  crc = 0x4611746a, v = "v1.2",  version = "0002", link = "https://raw.githubusercontent.com/Hack-Usagi/AnalogStickDisable/master/README.md", },
{ name = "AnalogStickDisable Right Only by Hack-Usagi", id = "ANALOGDISABLERIGHT.png", path = "AnalogStickDisable_RightOnly.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_ANALOGSTICK5"], KEY = "INSTALLP_DESC_ANALOGSTICK5",
  crc = 0x3ede7a18, v = "v1.2",  version = "0002", link = "https://raw.githubusercontent.com/Hack-Usagi/AnalogStickDisable/master/README.md", },
{ name = "AnalogStickDisable Right To Left by Yoti", id = "ANALOGDISABLERL.png", path = "AnalogStickDisable_RightToLeft.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_ANALOGSTICK2"], KEY = "INSTALLP_DESC_ANALOGSTICK2",
  crc = 0x368ef96e, v = "v1.2",  version = "0001", link = "https://raw.githubusercontent.com/Yoti/AnalogStickDisable/master/README.md", },
{ name = "AnalogStickDisable Swap Left To Right by Yoti", id = "ANALOGDISABLESWAP.png", path = "AnalogStickDisable_SwapLeftAndRight.skprx", section = "KERNEL", version = "0001", desc = LANGUAGE["INSTALLP_DESC_ANALOGSTICK3"], KEY = "INSTALLP_DESC_ANALOGSTICK3",
  crc = 0x3b4c5ba0, v = "v1.2",  version = "0001", link = "https://raw.githubusercontent.com/Yoti/AnalogStickDisable/master/README.md", },
{ name = "cidSpoofer by SilicaAndPina", id = "CIDSPOOFER.png", path = "cidSpoof.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_CIDSPOOF"], KEY = "INSTALLP_DESC_CIDSPOOF",
  crc = 0x9897db09, v = "v1.0",  version = "0001",  link = "https://silica.codes/SilicaAndPina/cidspoofer/raw/branch/master/README.md", },
{ name = "ds3vita by xerpi", id = "DS3VITA.png", path = "ds3vita.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_DS3VITA"], KEY = "INSTALLP_DESC_DS3VITA",
  crc = 0x6129a85e, v = "Beta3", version = "0001", link = "https://raw.githubusercontent.com/xerpi/ds3vita/hooks/README.md", },
{ name = "ds4vita by xerpi", id = "DS4VITA.png", path = "ds4vita.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_DS4VITA"], KEY = "INSTALLP_DESC_DS4VITA",
  crc = 0xd61110c1, v = "v1.2 hooks experimental", version = "0002", link = "https://raw.githubusercontent.com/xerpi/ds4vita/master/README.md", },
{ name = "ds34vita by MERLev", id = "DS34VITA.png", path = "ds34vita.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_DS34VITA"], KEY = "INSTALLP_DESC_DS34VITA",
  crc = 0x9e58d7e0, v = "v1.1",  version = "0002", link = "https://raw.githubusercontent.com/MERLev/ds34vita/master/README.md", },
{ name = "Kubridge by TheOfficialFloW/bythos14", id = "KUBRIDGE.png", path = "kubridge.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_KUBRIDGE"], KEY = "INSTALLP_DESC_KUBRIDGE",
  crc = 0xbfa0fd58, v = "v0.3", version = "0003", },
{ name = "NoNpDrm by TheOfficialFloW",	id = "NONPDRM.png", path = "nonpdrm.skprx",	section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_NONPDRM"], KEY = "INSTALLP_DESC_NONPDRM",
  crc = 0x1040b585, v = "v1.2",	version = "0001", link = "https://raw.githubusercontent.com/TheOfficialFloW/NoNpDrm/master/readme.md", },
{ name = "NoNpDrm Unofficial by LMAN",	id = "NONPDRM.png", path = "nonpdrm_un.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_NONPDRMU"], KEY = "INSTALLP_DESC_NONPDRMU",
  crc = 0x40704407, v = "v1.4", version = "0001", },
{ name = "NoPsmDrm by frangarcj", id = "NOPSMDRM.png", path = "nopsmdrm.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_NOPSMDRM"], KEY = "INSTALLP_DESC_NOPSMDRM",
  crc = 0x3db6dcfd, v = "v1.4", version = "0001", link = "https://raw.githubusercontent.com/frangarcj/NoPsmDrm/master/README.md", },
{ name = "NoAVLS by SilicaAndPina", id = "NOAVLS.png", path = "noavls.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_NOAVLS"], KEY = "INSTALLP_DESC_NOAVLS",
  crc = 0xdcbae19b, v = "v0.01", version = "0001", link = "https://silica.codes/SilicaAndPina/noavls/raw/branch/master/README.md", },
{ name = "Repatch reLoaded by SonicMastr", id = "REPATCHEX.png", path = "repatch_ex.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_REPATCHEX"], KEY = "INSTALLP_DESC_REPATCHEX",
  crc = 0xd0f55082, v = "v1.2 Hotfix", version = "0002", link = "https://raw.githubusercontent.com/SonicMastr/rePatch-reLoaded/master/README.md", },
{ name = "Repatch by dots-tb",	id = "REPATCH.png", path = "repatch.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_REPATCH"], KEY = "INSTALLP_DESC_REPATCH",
  crc = 0x56d22ee4, v = "v3.0", version = "0001", link = "https://raw.githubusercontent.com/dots-tb/rePatch-reDux0/master/README.md", },
{ name = "Repatch by dots-tb", id = "REPATCH.png", path = "repatch_4.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_REPATCH271"], KEY = "INSTALLP_DESC_REPATCH271",
  crc = 0xd5d2f0ee, v = "2.71", version = "0001", link = "https://raw.githubusercontent.com/dots-tb/rePatch-reDux0/master/README.md", },
{ name = "udcd_uvc by xerpi", id = "UDCD.png", path = "udcd_uvc.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_UDCDUVC"], KEY = "INSTALLP_DESC_UDCDUVC",
  crc = 0xfa41c483, v = "v1.7", version = "0004", link = "https://raw.githubusercontent.com/xerpi/vita-udcd-uvc/master/README.md", },
{ name = "udcd_uvc OLED by xerpi", id = "UDCD.png", path = "udcd_uvc_oled_off.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_UDCDUVCO"], KEY = "INSTALLP_DESC_UDCDUVCO",
  crc = 0x62c43e6, v = "v1.7", version = "0004", link = "https://raw.githubusercontent.com/xerpi/vita-udcd-uvc/master/README.md", },
{ name = "udcd_uvc LCD by xerpi", id = "UDCD.png", path = "udcd_uvc_lcd_off.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_UDCDUVCL"], KEY = "INSTALLP_DESC_UDCDUVCL",
  crc = 0x1a3f1c6a, v = "v1.7", version = "0004", link = "https://raw.githubusercontent.com/xerpi/vita-udcd-uvc/master/README.md", },
{ name = "usbmc by yifanlu", id = "USBMC.png", path = "usbmc.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_USBMC"], KEY = "INSTALLP_DESC_USBMC",
  crc = 0x89e44e51, v = "v6", version = "0001", link = "https://raw.githubusercontent.com/yifanlu/usbmc/master/README.md", },
{ name = "vitastick by xerpi", id = "VITASTICK.png", path = "vitastick.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_VITASTICK"], KEY = "INSTALLP_DESC_VITASTICK",
  crc = 0x57cb395c, v = "0.4.1 alpha", version = "0001", link = "https://raw.githubusercontent.com/xerpi/vitastick/master/README.md", },
{ name = "viimote by xerpi", id = "WIIMOTE.png", path = "viimote.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_VIIMOTE"], KEY = "INSTALLP_DESC_VIIMOTE",
  crc = 0xffe3bd6f, v = "v1.2", version = "0001", link = "https://raw.githubusercontent.com/xerpi/viimote/master/README.md", },
{ name = "Vitacheat by FinalCheat", id = "VITACHEAT.png", path = "vitacheat.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_VITACHEAT"], KEY = "INSTALLP_DESC_VITACHEAT",
  crc = 0x462e5634, v = "Z06 BETA FOR 3.65+", version = "0001", link = "https://raw.githubusercontent.com/r0ah/vitacheat/master/README.md", },
{ name = "Vitacheat by FinalCheat", id = "VITACHEAT.png", path = "vitacheat360.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_VITACHEAT2"], KEY = "INSTALLP_DESC_VITACHEAT2",
  crc = 0xac992e9b, v = "Z04 BETA FOR 3.60", version = "0001", link = "https://raw.githubusercontent.com/r0ah/vitacheat/master/README.md", },
{ name = "noled by reprep", id = "NOLED.png", path = "noled.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_NOLED"], KEY = "INSTALLP_DESC_NOLED",
  crc = 0x4ef47972, v = "v1.1", version = "0001", link = "https://raw.githubusercontent.com/rereprep/noled/master/README.md", },
{ name = "nosleep by NamelessGhoul0", id = "NOSLEEP.png", path = "nosleep.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_NOSLEEP"], KEY = "INSTALLP_DESC_NOSLEEP",
  crc = 0x48177849, v = "v1.1", version = "0001", link = "https://raw.githubusercontent.com/NamelessGhoul0/nosleep/master/README.md", },
{ name = "VideoDebug by SilicaAndPina", id = "VIDEODEBUG.png", path = "videoDebug.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_VIDEODBG"], KEY = "INSTALLP_DESC_VIDEODBG",
  crc = 0x55fa8e6, v = "v1.0", version = "0001", link = "https://silica.codes/SilicaAndPina/videodebug/raw/branch/master/README.md", },
{ name = "NoPowerLimits by Electry", id = "NOPOWERLIMITS.png", path = "NoPowerLimits.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_NOPOWERL"], KEY = "INSTALLP_DESC_NOPOWERL",
  crc = 0x506c9852, v = "v1.1", version = "0001", link = "https://raw.githubusercontent.com/Electry/NoPowerLimitsVita/master/README.md", },
{ name = "lolita500 by teakhanirons", id = "LOLITA.png", path = "lolita500.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_LOLITA"], KEY = "INSTALLP_DESC_LOLITA",
  crc = 0x17bbd4a8, v = "v1.0", version = "0001", link = "https://raw.githubusercontent.com/teakhanirons/lolita500/master/README.md", },
{ name = "lolita444 by teakhanirons", id = "LOLITA.png", path = "lolita444.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_LOLITA4"], KEY = "INSTALLP_DESC_LOLITA4",
  crc = 0x4affc1de, v = "v0.5", version = "0001", link = "https://raw.githubusercontent.com/teakhanirons/lolita500/master/README.md", },
{ name = "Music Premium by cuevavirus", id = "MUSICPREMIUM.png", path = "music_premium.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_MUPREMIUM"], KEY = "INSTALLP_DESC_MUPREMIUM",
  crc = 0x62a68ba7, v = "v1.0.6", version = "0002", link = "https://raw.githubusercontent.com/cuevavirus/MusicPremium/master/README.md", },
{ name = "déjàvu: Vita SaveState Plugin by TheOfficialFloW", id = "DEJAVU.png", path = "dejavu.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_DEJAVU"], KEY = "INSTALLP_DESC_DEJAVU",
  crc = 0x9f283319, v = "v0.01",  version = "0001",  link = "https://raw.githubusercontent.com/TheOfficialFloW/dejavu/master/README.md", },
{ name = "Staybrightby cuevavirus", id = "STAYBRIGHT.png", path = "staybright.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_STAYBRIGHT"], KEY = "INSTALLP_DESC_STAYBRIGHT",
  crc = 0x6cee21a, v = "v1.0.1", version = "0002", link = "https://raw.githubusercontent.com/cuevavirus/Staybright/master/README.md", },
{ name = "PSOneScrot by cuevavirus", id = "PSONESCROT.png", path = "psonescrot.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_PSONESCROT"], KEY = "INSTALLP_DESC_PSONESCROT",
  crc = 0x46faa10f, v = "v0.01", version = "0001", link = "https://raw.githubusercontent.com/cuevavirus/PSOneScrot/master/README.md", },
{ name = "Cpu Affinity Changer by GrapheneCt", id = "CPUAFFINITY.png", path = "CpuAffinityChanger.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_CPUAFFCHANGER"], KEY = "INSTALLP_DESC_CPUAFFCHANGER",
  crc = 0x730024b, v = "v.2.0", version = "0001",  link = "https://raw.githubusercontent.com/GrapheneCt/Affinity-Changer/master/README.md", },
{ name = "X1Vita by Ibrahim778", id = "X1VITA.png", path = "X1Vita.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_X1VITA"], KEY = "INSTALLP_DESC_X1VITA",
  crc = 0x39c66c44, v = "v3.3", version = "0002", link = "https://raw.githubusercontent.com/Ibrahim778/X1Vita/master/README.md" },
{ name = "vshPatch by KuromeSan", id = "VSHPATCH.png", path = "vshPatch.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_VSHPATCH"], KEY = "INSTALLP_DESC_VSHPATCH",
  crc = 0x9f618618, v = "v1.0", version = "0001", link = "https://raw.githubusercontent.com/KuromeSan/vshPatch/master/README.md", },
{ name = "PocketStationUnlocker by SilicaAndPina", id = "POCKETSTATION.png", path = "pocketstationunlocker.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_POCKETSTATION"], KEY = "INSTALLP_DESC_POCKETSTATION",
  crc  = 0x956f21d6, v = "v1.1", version = "0002", link = "https://silica.codes/SilicaAndPina/PocketstationUnlocker/raw/branch/master/README.md", },
{ name = "EmergencyMount by teakhanirons", id = "EMERGENCYMOUNT.png", path = "EmergencyMount.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_EMERGENCYMOUNT"], KEY = "INSTALLP_DESC_EMERGENCYMOUNT",
  crc = 0xaff88dd7, v = "v1.0", version = "0001", },
{ name = "CapUnlocker by GrapheneCt", id = "CAPUNLOCKER.png", path = "CapUnlocker.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_CAPUNLOCK"], KEY = "INSTALLP_DESC_CAPUNLOCK",
  crc = 0x8cebed84, v = "v1.4",  version = "0005",  link = "https://raw.githubusercontent.com/GrapheneCt/CapUnlocker/master/README.md", },
{ name = "ds4touch by MERLev", id = "DS4TOUCH.png", path = "ds4touch.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_DS4TOUCH"], KEY = "INSTALLP_DESC_DS4TOUCH",
  crc = 0x7b060dc4, v = "v1.1.3", version = "0004", link = "https://raw.githubusercontent.com/MERLev/ds4touch/master/README.md", },
{ name = "VolLightbarCtrlWithDS4 by CallmeBK", id = "VOLLIGHTBARDS4.png", path = "VolLightbarCtrlWithDS4.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_VOLLIGHTBAR_DS4"], KEY = "INSTALLP_DESC_VOLLIGHTBAR_DS4",
  crc = 0xf85a1bc3, v = "v1.1", version = "0001", link = "https://raw.githubusercontent.com/CallmeBK/VolLightbarCtrlWithDS4/master/README.md", },
{ name = "LCD Colour Space Changer by cuevavirus", id = "LCDCOLOUR.png",  path = "pspemu-colour-crunch.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_LCDSPACE"], KEY = "INSTALLP_DESC_LCDSPACE",
  crc = 0x85341adb, v = "v1.2.0", version = "0002", },
{ name = "FdFix by TheOfficialFloW", id = "FDFIX.png", path = "fd_fix.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_FDFIX"], KEY = "INSTALLP_DESC_FDFIX",
  crc = 0x34eb7b30, v = "v1.0", version = "0001", link = "https://raw.githubusercontent.com/TheOfficialFloW/FdFix/master/README.md", },
{ name = "reSavedata by Princess of Sleeping", id = "RESAVEDATA.png", path = "resavedata.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_RESAVEDATA"], KEY = "INSTALLP_DESC_RESAVEDATA",
  crc  = 0xce09ab41, v = "v1.0", version = "0002", },
{ name = "System-Integrated DualSense Driver for PlayStation TV by cuevavirus", id = "DUALSENSE.png", path = "dualsense-driver.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_DUALSENSE"], KEY = "INSTALLP_DESC_DUALSENSE",
  crc = 0xd88897b1, v = "v1.0", version = "0001", },
{ name = "PSVshell by Electry", id = "PSVSHELL.png", path = "PSVshell.skprx", section = "KERNEL", tai_del1 = "PSVshellPlus_Kernel.skprx", section_del1 = "KERNEL", tai_del2 = "PSVshellPlus_Shell.suprx", section_del2 = "main", desc = LANGUAGE["INSTALLP_DESC_PSVSHELL"], KEY = "INSTALLP_DESC_PSVSHELL",
  crc = 0xca688dc8, v = "v1.2 Beta",version = "0002", link = "https://raw.githubusercontent.com/Electry/PSVshell/master/README.md", },
{ name = "Magic Automatic Fake User Input by Rufis01", id = "MAFUINPUT.png", path = "MAFUinput.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_MAFUINPUT"], KEY = "INSTALLP_DESC_MAFUINPUT",
  crc = 0x6322adb1, v = "v2.0-Alpha.1", version = "0003", link = "https://raw.githubusercontent.com/Rufis01/MAFU-I/non-stop/README.MD", },
{ name = "ViXEn by isage", id = "VIXEN.png", path = "vixen.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_VIXEN"], KEY = "INSTALLP_DESC_VIXEN",
  crc = 0xc35f8c43, v = "v1.1", version = "0001", link = "https://raw.githubusercontent.com/isage/vixen/master/README.md", },

--Boot_config.txt
{ name = "Custom Boot Splash by Princess of Sleeping", id = "CUSTOMBOOTSPLASH.png", path = "custom_boot_splash.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_CUSTOMBOOTSPLASH"], KEY = "INSTALLP_DESC_CUSTOMBOOTSPLASH",
  crc = 0xc9ec5787, v = "v1.0", version = "0001",  link = "https://raw.githubusercontent.com/Princess-of-Sleeping/PSP2-CustomBootSplash/master/README.md", },

--{ name = "Monaural by cuevavirus v1.0.0", id = "MONAURAL.png", path = "monaural.skprx", section = "KERNEL", version = "0001", desc = LANGUAGE["INSTALLP_DESC_MONAURAL"], KEY = "INSTALLP_DESC_MONAURAL", link = "https://raw.githubusercontent.com/cuevavirus/monaural/master/README.md", },
--{ name = "DerInClocKS by teakhanirons v1.0", id = "DERINCLOCKS.png", path = "derinclocks.skprx", section = "KERNEL", version = "0001", desc = LANGUAGE["INSTALLP_DESC_DERIN"], KEY = "INSTALLP_DESC_DERIN", },
--{ name = "ioplus by dots-tb v0.1", path = "ioplus.skprx", id = "IOPLUS.png", section = "KERNEL", version = "0001", desc = LANGUAGE["INSTALLP_DESC_IOPLUS"], KEY = "INSTALLP_DESC_IOPLUS", link = "", },
--{ name = "LOLIcon by dots-tb v1.0.1.1 HOTFIX A", id = "LOLICON.png", path = "lolicon.skprx", section = "KERNEL", version = "0001", desc = LANGUAGE["INSTALLP_DESC_LOLICON"], KEY = "INSTALLP_DESC_LOLICON", link = "https://raw.githubusercontent.com/dots-tb/LOLIcon/master/README.md", },
--{ name = "RapidMenu by cuevavirus r1", id = "RAPIDMENU.png", path = "rapidmenu.skprx", section = "KERNEL", version = "0001", desc = LANGUAGE["INSTALLP_DESC_RAPIDMENU"], KEY = "INSTALLP_DESC_RAPIDMENU", link = "https://raw.githubusercontent.com/cuevavirus/Rapidmenu/master/README.md", },
--{ name = "CoreUnlocker80000H by GrapheneCt v1.0", id = "COREUNLOCKER.png", path = "CoreUnlocker80000H.skprx", section = "KERNEL", version = "0001", desc = LANGUAGE["INSTALLP_DESC_COREUNLOCK"], KEY = "INSTALLP_DESC_COREUNLOCK", link = "https://raw.githubusercontent.com/GrapheneCt/CoreUnlocker80000H/master/README.md", },

--with vpk
{ name = "VitaKeyboard by MarkOfTheLand", id = "VITAKEYBOARD.png", path = "hidkeyboard.skprx", section = "KERNEL", version = "0001", desc = LANGUAGE["INSTALLP_DESC_VITAKEYBOARD"], KEY = "INSTALLP_DESC_VITAKEYBOARD",
  crc = 0x6e8eee25, v = "v1.1", link = "https://raw.githubusercontent.com/mswlandi/vitakeyboard/master/README.md", vpk = string.format("https://github.com/%s/%s/raw/master/vpks/%s", APP_REPO, APP_PROJECT, "vitakeyboard.vpk"), },
{ name = "Sharpscale by cuevavirus", id = "SHARPSCALE.png", path = "sharpscale.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_SHARPSCALE"], KEY = "INSTALLP_DESC_SHARPSCALE",
  crc  = 0x7bec02d1, v = "v1.5.0", version = "0005", link = "https://raw.githubusercontent.com/cuevavirus/Sharpscale/master/README.md", vpk = string.format("https://github.com/%s/%s/raw/master/vpks/%s", APP_REPO, APP_PROJECT, "sharpscale_config.vpk"), },
{ name = "BetterTrackPlug by fmudanyali", id = "BETTERTRACKPLUG.png", path = "BetterTrackPlug.skprx", section = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_TRACKPLUGMOD"], KEY = "INSTALLP_DESC_TRACKPLUGMOD",
  crc = 0xd0b0c7ca, v = "1.1",  version = "0005",  link = "https://raw.githubusercontent.com/fmudanyali/BetterTrackPlug/master/README.md", vpk = string.format("https://github.com/%s/%s/raw/master/vpks/%s", APP_REPO, APP_PROJECT, "BetterTrackPlug.vpk"), }, 

--with config
{ name = "reF00D by FAPS Team", id = "REFOOD_SYSCALL.png", path = "reF00D.skprx", section = "KERNEL", config = "keys.bin", desc = LANGUAGE["INSTALLP_DESC_REFOOD"], KEY = "INSTALLP_DESC_REFOOD",
  crc = 0x31b1a1d, v = "v1.1", version = "0002", link = "https://raw.githubusercontent.com/dots-tb/reF00D/master/README.md", },
{ name = "Vitabright by devnoname120",	id = "VITABRIGHT.png", path = "vitabright.skprx", section = "KERNEL", config = "vitabright_lut.txt", desc = LANGUAGE["INSTALLP_DESC_VITABRIGHT"], KEY = "INSTALLP_DESC_VITABRIGHT",
  crc = 0x22a964a, v = "v2.0", version = "0003", link = "https://raw.githubusercontent.com/devnoname120/vitabright/master/README.md", },
{ name = "AnalogsEnhancer by Rinnegatamante/Yoti", id = "ANALOGSENHANCER.png", path = "AnalogsEnhancer.skprx", section = "KERNEL", config = "AnaEnCfg.txt", desc = LANGUAGE["INSTALLP_DESC_ANALOGSENHANCER"], KEY = "INSTALLP_DESC_ANALOGSENHANCER",
  crc = 0xf4df04d1, v = "v1.1-ur0", version = "0002", link = "https://raw.githubusercontent.com/Yoti/AnalogsEnhancer/master/README.md", },

--with config&configpath
{ name = "reAuth - Use PlayStation Store and sign-in by cuevavirus", id = "REAUTH.png", path = "reAuth.skprx", section = "KERNEL", config = "reAuth.zip", configpath = "ur0:data/", desc = LANGUAGE["INSTALLP_DESC_REAUTH"], KEY = "INSTALLP_DESC_REAUTH",
  crc = 0xc42994b3, v = "v1.0", version = "0001",  dl = "reAuth.zip", },

--2 prxs
{ name = "DSMotion by OperationNT414C", id = "DSMOTION.png", path = "dsmotion.skprx", section = "KERNEL", path2 = "dsmotion.suprx", section2 = "ALL", desc = LANGUAGE["INSTALLP_DESC_DSMOTION"], KEY = "INSTALLP_DESC_DSMOTION",
  crc = 0xe869fae2, v = "v1.2", crc2 = 0xa398acb7, version = "0001", link = "https://raw.githubusercontent.com/OperationNT414C/DSMotion/master/README.md", },
{ name = "MiniVitaTV by TheOfficialFloW", id = "MINIVITATV.png", path = "minivitatv.skprx", section = "KERNEL", path2 = "ds3.skprx", section2 = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_MINIVITATV"], KEY = "INSTALLP_DESC_MINIVITATV",
  crc = 0xa7cca609, v = "beta 0.5", crc2 = 0x981077fd, version = "0002", link = "https://raw.githubusercontent.com/TheOfficialFloW/MiniVitaTV/master/README.md", },
{ name = "reVita by MERLev", id = "REVITA.png", path = "reVita.skprx", section = "KERNEL", path2 = "ioplus.skprx", section2 = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_REVITA"], KEY = "INSTALLP_DESC_REVITA",
  crc = 0xc359f44b, v = "v1.0.8", crc2 = 0xe73bfd7b, version = "0003", dl = "reVitaMotion.suprx", link = "https://raw.githubusercontent.com/MERLev/reVita/master/README.md", },

--with config&configpath&2 prxs
{ name = "PSVshellPlus by GrapheneCt", id = "PSVSHELLPLUS.png", path = "PSVshellPlus_Kernel.skprx", section = "KERNEL", path2 = "PSVshellPlus_Shell.suprx", section2 = "main", config = "PSVshell.zip", configpath = "ur0:data/", tai_del1 = "PSVshell.skprx", section_del1 = "KERNEL",
  crc = 0x4f12065b, v = "v1.3", crc2 = 0xb126009b, version = "0002", dl = "PSVshell.zip", desc = LANGUAGE["INSTALLP_DESC_PSVSHELLPLUS"], KEY = "INSTALLP_DESC_PSVSHELLPLUS", link = "https://raw.githubusercontent.com/GrapheneCt/PSVshellPlus/main/README.md", },


--Main [SECTION]
{ name = "PasteUnlock by GrapheneCt", id = "PASTEUNLOCK.png", path = "PasteUnlock.suprx", section = "main", desc = LANGUAGE["INSTALLP_DESC_PASTEUNLOCK"], KEY = "INSTALLP_DESC_PASTEUNLOCK",
  crc = 0x854c33de, v = "v1.0", version = "0001", link = "https://raw.githubusercontent.com/GrapheneCt/PasteUnlock/main/README.md", },
{ name = "Download Enabler by TheOfficialFloW (VitaTweaks)", id = "DOWNLOADENABLER.png", path = "download_enabler.suprx", section = "main", desc = LANGUAGE["INSTALLP_DESC_DENABLER"], KEY = "INSTALLP_DESC_DENABLER",
  crc = 0xa53e557, v = "v5", version = "0001",  link = "https://raw.githubusercontent.com/TheOfficialFloW/VitaTweaks/master/README.md", },
{ name = "NoLockScreen by TheOfficialFloW (VitaTweaks)", id = "NOLOCKSCREEN.png", path = "nolockscreen.suprx", section = "main", desc = LANGUAGE["INSTALLP_DESC_NOLOCKSCREEN"], KEY = "INSTALLP_DESC_NOLOCKSCREEN",
  crc = 0x84c2cdd, v = "v2.0", version = "0001", link = "https://raw.githubusercontent.com/TheOfficialFloW/VitaTweaks/master/README.md", },
{ name = "NoTrophyMsg by TheOfficialFloW (VitaTweaks)", id = "NOTROPHYMSG.png", path = "notrophymsg.suprx", section = "main", desc = LANGUAGE["INSTALLP_DESC_NOTROPHYMSG"], KEY = "INSTALLP_DESC_NOTROPHYMSG",
  crc = 0x235bdde4, v = "v1.0", version = "0001", link = "https://raw.githubusercontent.com/TheOfficialFloW/VitaTweaks/master/README.md", },
{ name = "Shellbat by nowrep", path = "shellbat.suprx", id = "SHELLBAT.png", section = "main", desc = LANGUAGE["INSTALLP_DESC_SHELLBAT"], KEY = "INSTALLP_DESC_SHELLBAT",
  crc = 0xb8b8a12c, v = "vR10", version = "0001", link = "https://raw.githubusercontent.com/nowrep/vita-shellbat/master/README.md", },
{ name = "Shellbat Mod by devnoname120", id = "SHELLBATMOD.png", path = "shellbat_mod.suprx", section = "main", desc = LANGUAGE["INSTALLP_DESC_SHELLBATM"], KEY = "INSTALLP_DESC_SHELLBATM",
  crc = 0x3a333a73, v = "vR10", version = "0001", link = "https://raw.githubusercontent.com/nowrep/vita-shellbat/master/README.md", },
{ name = "Shellsecbat by OperationNT414C", id = "SHELLSECBAT.png", path = "shellsecbat.suprx", section = "main", desc = LANGUAGE["INSTALLP_DESC_SHELLSECBAT"], KEY = "INSTALLP_DESC_SHELLSECBAT",
  crc = 0xf9376dd1, v = "v10", version = "0001", link = "https://raw.githubusercontent.com/OperationNT414C/ShellSecBat/master/README.md", },
{ name = "pngshot by xyzz", id = "PNGSHOOT.png", path = "pngshot.suprx", section = "main", desc = LANGUAGE["INSTALLP_DESC_PNGSHOT"], KEY = "INSTALLP_DESC_PNGSHOT",
  crc = 0x15662801, v = "v1.3", version = "0001", link = "https://raw.githubusercontent.com/xyzz/pngshot/master/README.md", },
{ name = "Vflux by Applelo", id = "VFLUX.png", path = "vflux.suprx", section = "main", desc = LANGUAGE["INSTALLP_DESC_VFLUX"], KEY = "INSTALLP_DESC_VFLUX",
  crc = 0xf3fd6b34, v = "v0.5", version = "0001", link = "https://raw.githubusercontent.com/Applelo/vFlux/master/README.md", },
{ name = "reSkype by SilicaAndPina", id = "RESKYPE.png", path = "reSkype.suprx", section = "main", desc = LANGUAGE["INSTALLP_DESC_RESKYPE"], KEY = "INSTALLP_DESC_RESKYPE",
  crc = 0xbaab9ab, v = "v1.0", version = "0001", link = "https://silica.codes/SilicaAndPina/reskype/raw/branch/master/README.md", },
{ name = "Autoboot by Rinnegatamante (only for 3.60/3.65)", id = "AUTOBOOT.png", path = "AutoBoot.suprx", section = "main", desc = LANGUAGE["INSTALLP_DESC_AUTOBOOT"], KEY = "INSTALLP_DESC_AUTOBOOT",
  crc = 0x96aca7bb, v = "v1.2",  version = "0001", },
{ name = "Vitacompanion by devnoname120", id = "VITACOMPANION.png", path = "vitacompanion.suprx", section = "main", desc = LANGUAGE["INSTALLP_DESC_VITACOMPA"], KEY = "INSTALLP_DESC_VITACOMPA",
  crc = 0x1ff62f7c, v = "v1.00", version = "0001", link = "https://raw.githubusercontent.com/devnoname120/vitacompanion/master/README.md", },
{ name = "volume_profile by cuevavirus", id = "JAV.png", path = "jav.suprx", section = "main", desc = LANGUAGE["INSTALLP_DESC_VOLUPROF"], KEY = "INSTALLP_DESC_VOLUPROF",
  crc = 0xa2a68c2e, v = "v2.2.0", version = "0002", link = "https://raw.githubusercontent.com/cuevavirus/jav/master/README.md", },
{ name = "DolcePolce by SilicaAndPina", id = "DOLCEPOLCE.png", path = "DolcePolce.suprx", section = "main", desc = LANGUAGE["INSTALLP_DESC_DOLCEPOLCE"], KEY = "INSTALLP_DESC_DOLCEPOLCE",
  crc = 0x3369f6f1, v = "v1.0", version = "0001",  link = "https://silica.codes/SilicaAndPina/dolcepolce/raw/branch/master/README.md",  },
{ name = "LowMemMode by GrapheneCt", id = "LOWMEMMODE.png", path = "LowMemMode.suprx", section = "main", desc = LANGUAGE["INSTALLP_DESC_LOWMEMMODE"], KEY = "INSTALLP_DESC_LOWMEMMODE",
  crc = 0x4d940765, v = "v1.2", version = "0002", link = "https://raw.githubusercontent.com/GrapheneCt/LowMemMode/master/README.md", },
{ name = "QAscreenshot by GrapheneCt", id = "QASCREENSHOT.png", path = "QAscreenshot.suprx", section = "main", desc = LANGUAGE["INSTALLP_DESC_QASCREEN"], KEY = "INSTALLP_DESC_QASCREEN",
  crc = 0xe5f3d461, v = "v1.1", version = "0001", link = "https://raw.githubusercontent.com/GrapheneCt/QAscreenshot/master/README.md", },
{ name = "NoSharedFb by GrapheneCt", id = "NOSHAREDFB.png", path = "NoSharedFb.suprx", section = "main", desc = LANGUAGE["INSTALLP_DESC_NOSHAREDFB"], KEY = "INSTALLP_DESC_NOSHAREDFB",
  crc = 0x109db89e, v = "v1.0", version = "0002", link = "https://raw.githubusercontent.com/GrapheneCt/NoSharedFb/master/README.md", },
{ name = "TrophyShot by FMudanyali", id = "TROPHYSHOT.png", path = "TrophyShot.suprx", section = "main", tai_del1 = "TrophyShot_shell.suprx", section_del1 = "main", tai_del2 = "TrophyShot_app.suprx", section_del2 = "ALL", desc = LANGUAGE["INSTALLP_DESC_TROPHYSHOT"], KEY = "INSTALLP_DESC_TROPHYSHOT",
  crc = 0xc96daf46, v = "v1.1.1.1", version = "0003", link = "https://raw.githubusercontent.com/FMudanyali/TrophyShot/master/README.md", },
{ name = "BootSound by teakhanirons", id = "BOOTSOUND.png", path = "bootsound.suprx", section = "main", desc = LANGUAGE["INSTALLP_DESC_BOOTSOUND"], KEY = "INSTALLP_DESC_BOOTSOUND",
  crc = 0x4dfd2466, v = "v1.0", version = "0002", },
{ name = "Quick Menu Plus by cuevavirus", id = "QUICKMENU.png", path = "quickmenuplus.suprx", section = "main", desc = LANGUAGE["INSTALLP_DESC_QUICKMENU"], KEY = "INSTALLP_DESC_QUICKMENU",
  crc = 0xe9d642fe, v = "v2.0.0", version = "0001", link = "https://git.shotatoshounenwachigau.moe/vita/quickmenuplus/plain/CHANGELOG.md", },
{ name = "dt2s-vita by joel16", id = "DT2SBAR.png", path = "dt2s_statusbar.suprx", section = "main", tai_del1 = "dt2s.suprx", section_del1 = "ALL", desc = LANGUAGE["INSTALLP_DESC_DT2S_STATUSBAR"], KEY = "INSTALLP_DESC_DT2S_STATUSBAR",
  crc = 0x51fadce9, v = "v1.1 DoubleTap2Sleep (StatusBar)", version = "0002", link = "https://raw.githubusercontent.com/joel16/dt2s-vita/main/README.md", },
{ name = "Fruitpeel by cuevavirus", id = "FRUITPEEL.png", path = "fruitpeel.suprx", section = "main", desc = LANGUAGE["INSTALLP_DESC_FRUITPEEL"], KEY = "INSTALLP_DESC_FRUITPEEL",
  crc = 0xfd02ee75, v = "v1.0", version = "0001", },
{ name = "USBDisable by Ibrahim778", id = "USBDISABLE.png", path = "USBDisable.suprx", section = "main", desc = LANGUAGE["INSTALLP_DESC_USBDISABLE"], KEY = "INSTALLP_DESC_USBDISABLE",
  crc = 0x03afb806, v = "v3.02", version = "0003", link = "https://raw.githubusercontent.com/Ibrahim778/USBDisable/master/README.md", },
{ name = "ftpeverywhere by teakhanirons", id = "FTPEVERYWHERE.png", path = "ftpeverywhere.suprx", section = "main", desc = LANGUAGE["INSTALLP_DESC_FTPEVERYWHERE"], KEY = "INSTALLP_DESC_FTPEVERYWHERE",
  crc = 0x2b650ebd, v = "v1.0", version = "0001", link = "https://raw.githubusercontent.com/teakhanirons/ftpeverywhere/master/README.md", },

--{ name = "Quick Power by cuevavirus v1.1.0", id = "QUICKPOWER.png", path = "quick_power.suprx", section = "main", version = "0001", desc = LANGUAGE["INSTALLP_DESC_QUICKPOWER"], KEY = "INSTALLP_DESC_QUICKPOWER", link = "https://raw.githubusercontent.com/cuevavirus/QuickPower/master/README.md", },
--{ name = "Quick Volume by cuevavirus v1.2.1", id = "QUICKVOLUME.png", path = "quick_volume.suprx", section = "main", version = "0001", desc = LANGUAGE["INSTALLP_DESC_QUICKVOLUME"], KEY = "INSTALLP_DESC_QUICKVOLUME", link = "https://raw.githubusercontent.com/cuevavirus/QuickVolume/master/README.md", },

--With config
{ name = "Custom Warning by TheOfficialFloW (VitaTweaks)", id = "CUSTOMWARNING.png", path = "custom_warning.suprx", section = "main", config = "custom_warning.txt", desc = LANGUAGE["INSTALLP_DESC_CUSTOMWARNING"], KEY = "INSTALLP_DESC_CUSTOMWARNING",
  crc = 0xb08d3450, v = "v2", version = "0001",  link = "https://raw.githubusercontent.com/TheOfficialFloW/VitaTweaks/master/README.md", },

--with config&configpath
{ name = "TransparentImpose by GrapheneCt", id = "TRANSIMPOSE.png", path = "TrImpose.suprx", section = "main", config = "trimpose.txt", configpath = "ur0:data/", desc = LANGUAGE["INSTALLP_DESC_TRIMPOSE"], KEY = "INSTALLP_DESC_TRIMPOSE",
  crc = 0x72ed507a, v = "v1.0", version = "0001", link = "https://raw.githubusercontent.com/GrapheneCt/TransparentImpose/master/README.md", },
{ name = "QuickLauncher by Ibrahim778 (QuickMenuReborn)", id = "QUICKLAUNCHER.png", path = "QuickMenuReborn.suprx", section = "main", config = "QuickMenuReborn.zip", configpath = "ur0:/", desc = LANGUAGE["INSTALLP_DESC_QUICKLAUNCHER"], KEY = "INSTALLP_DESC_QUICKLAUNCHER",
  crc = 0x6acf244c, v = "v1.2", crc2 = 0x83f771ea, version = "0001",  dl = "QuickMenuReborn.zip", link = "https://raw.githubusercontent.com/Ibrahim778/QuickLauncher/master/README.md", },
{ name = "psp2wpp by Princess of Sleeping", id = "PSP2WPP.png", path = "psp2wpp.suprx", section = "main", config = "waveparam.txt", configpath = "ux0:data/", desc = LANGUAGE["INSTALLP_DESC_WAVE"], KEY = "INSTALLP_DESC_WAVE",
  crc = 0x981d7d15, v = "v1.0", version = "0001", dl = "waveparam.bin", link = "https://raw.githubusercontent.com/Princess-of-Sleeping/psp2wpp/master/README.md", },

--2 prxs
{ name = "Quietshot by cuevavirus", id = "QUIETSHOT.png", path = "quietshot.suprx", section = "main", path2 = "quietshot.suprx", section2 = "NPXS10095", desc = LANGUAGE["INSTALLP_DESC_QUIETSHOT"], KEY = "INSTALLP_DESC_QUIETSHOT",
  crc = 0x513a6d51, v = "v1.0", version = "0001", link = "https://raw.githubusercontent.com/cuevavirus/Quietshot/master/README.md", },


--All [SECTION]
{ name = "Vita3g-disable by VictorGamer072YT", id = "3GDISABLE.png", path = "vita3g-disable.suprx", section = "ALL", desc = LANGUAGE["INSTALLP_DESC_3GDISABLE"], KEY = "INSTALLP_DESC_3GDISABLE",
  crc = 0x46f0321e, v = "v1.0", version = "0001", link = "https://raw.githubusercontent.com/VictorGamer072YT/vita3g-disable/main/README.md", },
{ name = "VGi by Electry", id = "VGI.png", path = "VGi.suprx", section = "ALL", desc = LANGUAGE["INSTALLP_DESC_VGI"], KEY = "INSTALLP_DESC_VGI",
  crc = 0xfb309de3, v = "v0.7", version = "0001", link = "https://raw.githubusercontent.com/Electry/VGi/master/README.md", },
{ name = "TropHAX by SilicaAndPina", id = "TROPHAX.png", path = "trophax2.0.suprx", section = "ALL", desc = LANGUAGE["INSTALLP_DESC_TROPHAX"], KEY = "INSTALLP_DESC_TROPHAX",
  crc = 0xcebb8abb, v = "v2.0", version = "0001", link = "https://silica.codes/SilicaAndPina/trophax/raw/branch/master/README.md", },
{ name = "InfiniteNet by Rinnegatamante", id = "INFINITYNET.png", path = "InfiniteNet.suprx", section = "ALL", desc = LANGUAGE["INSTALLP_DESC_INFINITENET"], KEY = "INSTALLP_DESC_INFINITENET",
  crc = 0x4d001997, v = "v1.0", version = "0001", },
{ name = "FreePSM by SilicaAndPina", id = "FREEPSM.png", path = "FreePSM.suprx", section = "ALL", desc = LANGUAGE["INSTALLP_DESC_FREEPSM"], KEY = "INSTALLP_DESC_FREEPSM",
  crc = 0x3170b902, v = "v1.1", version = "0001", link = "https://silica.codes/SilicaAndPina/freepsm/raw/branch/master/README.md", },
{ name = "ScoreHax by SilicaAndPina", id = "SCOREHAX.png", path = "ScoreHax.suprx", section = "ALL", desc = LANGUAGE["INSTALLP_DESC_SCOREHAX"], KEY = "INSTALLP_DESC_SCOREHAX",
  crc = 0xac07756d, v = "v1.0", version = "0001", link = "https://raw.githubusercontent.com/KuromeSan/ScoreHax/master/README.md", },
{ name = "WDNR by Rinnegatamante", id = "WDNR.png", path = "WDNR.suprx", section = "ALL", desc = LANGUAGE["INSTALLP_DESC_WDNR"], KEY = "INSTALLP_DESC_WDNR",
  crc = 0xd096c8ba, v = "v1.0", version = "0001", },
{ name = "WDNF by EchoDev & Rinnegatamante", id = "WDNF.png", path = "WDNF.suprx", section = "ALL", desc = LANGUAGE["INSTALLP_DESC_WDNF"], KEY = "INSTALLP_DESC_WDNF",
  crc = 0xe2578384, v = "v1.0", version = "0001", },
{ name = "ShowInfo Lite by Yoti", id = "SHOWINFOLITE.png", path = "ShowInfoLite.suprx", section = "ALL", desc = LANGUAGE["INSTALLP_DESC_SHOWINFO"], KEY = "INSTALLP_DESC_SHOWINFO",
  crc = 0xa5cac382, v = "v0.2", version = "0001", },
{ name = "ShowInfo Full by Yoti", id = "SHOWINFOFULL.png", path = "ShowInfo.suprx", section = "ALL", desc = LANGUAGE["INSTALLP_DESC_SHOWINFOFU"], KEY = "INSTALLP_DESC_SHOWINFOFU",
  crc = 0x9420f9c2, v = "v0.6", version = "0001", },
{ name = "Volume Control Pack by GrapheneCt", id = "VOLUMECTRL.png", path = "ModalVol.suprx", section = "ALL", desc = LANGUAGE["INSTALLP_DESC_MODALVOL"], KEY = "INSTALLP_DESC_MODALVOL",
  crc = 0xc7e873f6, v = "v1.0", version = "0001", link = "https://raw.githubusercontent.com/GrapheneCt/Volume-Control-Pack/master/README.md", },
--{ name = "hide-autoplugin by SilicaAndPina", id = "HIDEAP.png", path = "hide-autoplugin.suprx", section = "ALL", desc = LANGUAGE["INSTALLP_DESC_HIDEAP"], KEY = "INSTALLP_DESC_HIDEAP", link = "https://silica.codes/SilicaAndPina/hide-autoplugin/raw/branch/main/README.md",
--  crc = 0x3282486c , v = "v1.0", version = "0001", },

--{ name = "dt2s-vita v1.1 DoubleTap2Sleep for PS VITA by joel16", id = "DT2S.png", path = "dt2s.suprx", section = "ALL", tai_del1 = "dt2s_statusbar.suprx", section_del1 = "main", version = "0002", desc = LANGUAGE["INSTALLP_DESC_DT2S"], KEY = "INSTALLP_DESC_DT2S", link = "https://raw.githubusercontent.com/joel16/dt2s-vita/main/README.md", },
--{ name = "Oclock Vita by frangarcj v1.2.1", id = "OCLOCKVITA.png", path = "oclockvita.suprx", section = "ALL", version = "0001", desc = LANGUAGE["INSTALLP_DESC_OVERCLOCK"], KEY = "INSTALLP_DESC_OVERCLOCK", link = "https://raw.githubusercontent.com/frangarcj/oclockvita/master/README.md", },
--{ name = "Framecounter by Rinnegatamante v1.2", id = "FRAMECOUNTER.png", path = "Framecounter.suprx", section = "ALL", version = "0001", desc = LANGUAGE["INSTALLP_DESC_FRAMECOUNTER"], KEY = "INSTALLP_DESC_FRAMECOUNTER", },
--{ name = "FuckPSSE by SilicaAndPina v1.1", id = "FPSSE.png", path = "FuckPSSE.suprx", section = "ALL", version = "0001", desc = LANGUAGE["INSTALLP_DESC_FUCKPSSE"], KEY = "INSTALLP_DESC_FUCKPSSE", link = "https://silica.codes/SilicaAndPina/fuckpsse/raw/branch/master/README.md", },
--{ name = "PSMPatch by SilicaAndPina v1.1", id = "PSMPATCH.png", path = "PSMPatch.suprx", section = "ALL", version = "0001", desc = LANGUAGE["INSTALLP_DESC_PSMPATCH"], KEY = "INSTALLP_DESC_PSMPATCH", link = "https://silica.codes/SilicaAndPina/psmpatch/raw/branch/master/README.md", },


--2 prxs
{ name = "MakePsmGreatAgain by SilicaAndPina", id = "MAKEPSM.png", path = "MakePsmGreatAgain.suprx", section = "PCSI00007", path2 = "MakePsmGreatAgain.suprx", section2 = "PCSI00009", desc = LANGUAGE["INSTALLP_DESC_MAKEPSM"], KEY = "INSTALLP_DESC_MAKEPSM",
  crc = 0xe6a1ad4b, v = "v1.5", version = "0003", link = "https://silica.codes/SilicaAndPina/makepsmgreatagain/raw/branch/master/README.md", },
{ name = "PSV-VSH MENU by joel16", id = "VSHMENU.png", path = "vsh.suprx", section = "ALL", path2 = "kuio.skprx", section2 = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_VSHMENU"], KEY = "INSTALLP_DESC_VSHMENU",
  crc = 0x20db832d, v = "v3.4", crc2 = 0xeb053532, version = "0001", link = "https://raw.githubusercontent.com/joel16/PSV-VSH-Menu/master/README.md", },-- Need kuio.skprx
{ name = "VitaGrafix by Electry", id = "VITAGRAFIX.png", path = "VitaGrafix.suprx", section = "ALL", path2 = "ioplus.skprx", section2 = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_VITAGRAFIX"], KEY = "INSTALLP_DESC_VITAGRAFIX",
  crc = 0x87bdc6f8, v = "v5.0.2", crc2 = 0xe73bfd7b, version = "0001", link = "https://raw.githubusercontent.com/Electry/VitaGrafix/master/README.md", },
{ name = "TurboPad Mod by Yoti", id = "TURBOPAD.png", path = "TurboPad.suprx", section = "ALL", path2 = "ioplus.skprx", section2 = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_TURBOPAD"], KEY = "INSTALLP_DESC_TURBOPAD",
  crc = 0x26bf7c11, v = "v0.3", crc2 = 0xe73bfd7b, version = "0002", },
{ name = "reRescaler by Rinnegatamante", id = "RERESCALER.png", path = "reRescaler.suprx", section = "ALL", path2 = "ioplus.skprx", section2 = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_RESCALER"], KEY = "INSTALLP_DESC_RESCALER",
  crc = 0xbb465f67, v = "v1.0", crc2 = 0xe73bfd7b, version = "0001", },
{ name = "remaPSV by Rinnegatamante", id = "REMAPPSV1.png", path = "remaPSV.suprx", section = "ALL", path2 = "ioplus.skprx", section2 = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_REMAPSV"], KEY = "INSTALLP_DESC_REMAPSV",
  crc = 0xb7496a2c, v = "v1.1", crc2 = 0xe73bfd7b, version = "0001", },
{ name = "remaPSV by MERLev", id = "REMAPPSV2.png", path = "remaPSV2.suprx", section = "ALL", path2 = "ioplus.skprx", section2 = "KERNEL", desc = LANGUAGE["INSTALLP_DESC_REMAPSV2"], KEY = "INSTALLP_DESC_REMAPSV2",
  crc = 0xf4f5893b, v = "v2.0.2", crc2 = 0xe73bfd7b, version = "0002", link = "https://raw.githubusercontent.com/MERLev/remaPSV2/master/README.md", },

--{ name = "forcelang by xdanieldzd v0.2U", id = "FORCELANG.png", path = "forcelang.suprx", section = "ALL", path2 = "ioplus.skprx", section2 = "KERNEL", version = "0001", desc = LANGUAGE["INSTALLP_DESC_FORCELANG"], KEY = "INSTALLP_DESC_FORCELANG", link = "https://raw.githubusercontent.com/xdanieldzd/forcelang/master/README.md", },


--*PCSC80012
{ name = "HonRipper by GrapheneCt", id = "HONRIPPER.png", path = "HonRipper.suprx", section = "PCSC80012", desc = LANGUAGE["INSTALLP_DESC_HONRIPPER"], KEY = "INSTALLP_DESC_HONRIPPER",
  crc = 0xbef04e02, v = "v1.0", version = "0001", link = "https://raw.githubusercontent.com/GrapheneCt/HonRipper/master/README.md", },
--*NPXS10013
{ name = "vita-ps4linkcontrols by nowrep", id = "PS4LINK.png", path = "ps4linkcontrols.suprx", section = "NPXS10013", desc = LANGUAGE["INSTALLP_DESC_PS4LINK"], KEY = "INSTALLP_DESC_PS4LINK",
  crc = 0x6510993c, v = "vR7", version = "0001", link = "https://raw.githubusercontent.com/nowrep/vita-ps4linkcontrols/master/README.md", },
--NPXS10015 and *NPXS10016
{ name = "vita-macspoofer by Freakler", id = "MACSPOOFER.png", path = "macspoofer.suprx", section = "NPXS10015", path2 = "macspoofer.suprx", section2 = "NPXS10016", desc = LANGUAGE["INSTALLP_DESC_MACSPOOF"], KEY = "INSTALLP_DESC_MACSPOOF",
  crc = 0xe91bb868, v = "v1.0", version = "0001", link = "https://raw.githubusercontent.com/Freakler/vita-macspoofer/master/README.md", },
{ name = "Sysident by Princess of Sleeping", id = "SYSIDENT.png", path = "sysident.suprx", section = "NPXS10015", path2 = "sysident.suprx", section2 = "NPXS10016", desc = LANGUAGE["INSTALLP_DESC_SYSIDENT"], KEY = "INSTALLP_DESC_SYSIDENT",
  crc = 0xd96175f3, v = "v1.1", crc2 = 0x60e80e97, version = "0001", dl = "sysident.skprx", link = "https://raw.githubusercontent.com/cuevavirus/sysident/master/README.md", },
--NPXS10036
{ name = "reScreeny by dots_tb", id = "RESCREENY.png", path = "reScreeny.suprx", section = "NPXS10036", desc = LANGUAGE["INSTALLP_DESC_RESCREENY"], KEY = "INSTALLP_DESC_RESCREENY",
  crc = 0x2cb0f15f, v = "v1.2", version = "0001", link = "https://raw.githubusercontent.com/dots-tb/reScreeny/master/README.md", },
--NPXS10010
--{ name = "DePlayEnabler by alpakeno v1.0", id = "DEPLAYENABLER.png",  path = "deplayenabler.suprx", section = "NPXS10010", config = "deplayenabler.txt", version = "0001", desc = LANGUAGE["INSTALLP_DESC_DEPLAYENABLER"], KEY = "INSTALLP_DESC_DEPLAYENABLER", link = "https://raw.githubusercontent.com/alpakeno/DePlayEnabler/master/README.md", },

--Special P4 Golden HD
{ name = "Persona 4 Golden HD 1920x1080", id = "PERSONA4GOLDENHD.png", path = "p4goldenhd_1920x1080.suprx", desc = LANGUAGE["P4G_1920x1080_DESC"], KEY = "P4G_1920x1080_DESC", REMOVE = true,
  crc = 0x16e6c65d, v = "v1.0.1", version = "0001", },
{ name = "Persona 4 Golden HD 1280x720", id = "PERSONA4GOLDENHD.png", path = "p4goldenhd_1280x720.suprx", desc = LANGUAGE["P4G_1280x720_DESC"], KEY = "P4G_1280x720_DESC", REMOVE = true,
  crc = 0xab0e81cc, v = "v1.0.1",version = "0001", },
--Special Catherine Full Body HD
{ name = "Catherine Full Body HD 1280x720", id = "CATHERINEHD.png", path = "catherinefbhd.suprx", desc = LANGUAGE["MENU_PSVITA_INSTALL_P4G_HD_DESC"], KEY = "MENU_PSVITA_INSTALL_P4G_HD_DESC", REMOVE = true,
  crc = 0xb1829bcf, v = "v1.2.0", version = "0001", },
-- Special Vita-Nearest-Neighbour
{ name = "Vita-Nearest-Neighbour by MuxaJlbl4", id = "VITANEARESTN.png", path = "VitaNearestNeighbour.suprx", desc = LANGUAGE["INSTALLP_DESC_VITANEARESTN"], KEY = "INSTALLP_DESC_VITANEARESTN",
  crc = 0x2b24ba03, v = "v1.0", version = "0001", link = "https://raw.githubusercontent.com/MuxaJlbl4/Vita-Nearest-Neighbour/main/README.md", REMOVE = true, },
-- GameSDCard
{ name = "StorageMgr by CelesteBlue & Yoti (SD2VITA)", path = "storagemgr.skprx", section = "KERNEL", desc = LANGUAGE["MENU_PSVITA_INSTALL_SD2VITA_DESC"], KEY = "MENU_PSVITA_INSTALL_SD2VITA_DESC", REMOVE = true,
  crc = 0x8e496388, v = "v3.4",version = "0001",link = "https://raw.githubusercontent.com/RealYoti/StorageMgr/master/README.md", },



}
