-- Constants
APP_REPO = "ONElua"
APP_PROJECT = "AutoPlugin2"--Test
APP_FOLDER = "AUTOPLUG2"

APP_VERSION_MAJOR = 0x02 -- major.minor
APP_VERSION_MINOR = 0x16
APP_VERSION = ((APP_VERSION_MAJOR << 0x18) | (APP_VERSION_MINOR << 0x10)) -- Union Binary
